name: flutter_unit_and_widget_tests
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.0"

dependencies:
  flutter:
    sdk: flutter
  mocktail: ^0.3.0
  bloc: ^8.0.3
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
